In [1]:
# encoding: utf-8

import numpy as np
import struct
import matplotlib.pyplot as plt
import pandas as pd
import csv
from skimage import io
from PIL import Image
import cv2

In [22]:
path="E:\datasets\英雄联盟\data_test\data_test_set_cluster_0.npz"
data=np.load(path)
x_train=data["images"]
y_train=data["boxes"]
print(len(y_train))
for i in range(2):
    print(x_train[i])
    im = Image.fromarray(x_train[i])
    im.show()


448
[[[ 52  60  39]
  [ 82  84  63]
  [108 103  81]
  ...
  [ 12  33  14]
  [ 15  38  10]
  [  2  27   0]]

 [[113 117  84]
  [114 111  80]
  [112 103  74]
  ...
  [ 13  34  15]
  [ 14  39  10]
  [  0  27   0]]

 [[129 126  91]
  [106 100  68]
  [101  87  60]
  ...
  [ 12  35  15]
  [ 14  40  11]
  [  0  27   0]]

 ...

 [[ 55  55  47]
  [ 55  56  50]
  [ 55  56  48]
  ...
  [ 57  60  49]
  [ 45  57  35]
  [ 15  31   2]]

 [[ 75  72  65]
  [ 73  73  65]
  [ 72  72  64]
  ...
  [ 69  71  60]
  [ 58  66  45]
  [ 26  39  13]]

 [[ 61  58  49]
  [ 61  58  49]
  [ 59  56  47]
  ...
  [ 63  60  51]
  [ 62  66  49]
  [ 38  48  23]]]
[[[ 81  82  66]
  [112 113  95]
  [108 111  90]
  ...
  [ 11  32  13]
  [ 18  42  18]
  [  7  31   5]]

 [[115 114  96]
  [116 115  94]
  [103 103  79]
  ...
  [ 10  33  13]
  [ 17  41  17]
  [  5  29   3]]

 [[120 115  96]
  [111 106  84]
  [100  96  71]
  ...
  [  7  32  11]
  [ 13  39  14]
  [  0  26   0]]

 ...

 [[ 63  56  48]
  [ 62  55  49]
  [ 61  56  50]
